export const GET_ENTERTAINMENT_REQUEST = 'GET_ENTERTAINMENT_REQUEST'
export const GET_ENTERTAINMENT_SUCCESS = 'GET_ENTERTAINMENT_SUCCESS'
export const GET_ENTERTAINMENT_FAILURE = 'GET_ENTERTAINMENT_FAILURE'

export const ADD_ENTERTAINMENT_REQUEST = 'ADD_ENTERTAINMENT_REQUEST'
export const ADD_ENTERTAINMENT_SUCCESS = 'ADD_ENTERTAINMENT_SUCCESS'
export const ADD_ENTERTAINMENT_FAILURE = 'ADD_ENTERTAINMENT_FAILURE'

export const EDIT_ENTERTAINMENT_REQUEST = 'EDIT_ENTERTAINMENT_REQUEST'
export const EDIT_ENTERTAINMENT_SUCCESS = 'EDIT_ENTERTAINMENT_SUCCESS'
export const EDIT_ENTERTAINMENT_FAILURE = 'EDIT_ENTERTAINMENT_FAILURE'

export const DELETE_ENTERTAINMENT_REQUEST = 'DELETE_ENTERTAINMENT_REQUEST'
export const DELETE_ENTERTAINMENT_SUCCESS = 'DELETE_ENTERTAINMENT_SUCCESS'
export const DELETE_ENTERTAINMENT_FAILURE = 'DELETE_ENTERTAINMENT_FAILURE'
