export const GET_DATA_REQUEST = 'GET_DATA_REQUEST'
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS'
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE'

export const GET_FINANCE_REQUEST = 'GET_FINANCE_REQUEST'
export const GET_FINANCE_SUCCESS = 'GET_FINANCE_SUCCESS'
export const GET_FINANCE_FAILURE = 'GET_FINANCE_FAILURE'

export const GET_HEADLINES_REQUEST = 'GET_HEADLINES_REQUEST'
export const GET_HEADLINES_SUCCESS = 'GET_HEADLINES_SUCCESS'
export const GET_HEADLINES_FAILURE = 'GET_HEADLINES_FAILURE'
